### ISSUE TITLE
91 7e (LENGTH_ERROR)

### ISSUE THREAD

**Issue by KevinBeckers** [andrade/nfcjlib#1]
On every example I run I get a 917e (LENGTH_ERROR).
I am using a desfire ev1 4k

**Comment by andrade** [comment]
Do you mean the examples on the sample directory?

[This example](https://github.com/Andrade/nfcjlib/blob/master/src/nfcjlib/sample/ExampleAuth.java) is a simple test to see if things are working. Your DESFire EV1 card is assumed to be using the default key and cipher type (key is all zeros and cipher type is AES).
